<template>
  <v-container class="bg pl-10 pt-10">
      
    <div class="text-h5 font-weight-medium">
      Tabela de EFRAUs
    </div>

    <v-flex style="overflow: auto; max-height: 100vh;">
      <v-data-table :headers="headers" :items="items">
      </v-data-table>
    </v-flex>

  </v-container>
</template>


<style>
.bg {
  background: url('https://img.freepik.com/fotos-gratis/fundo-branco-elegante-com-linhas-de-ondas-azuis_1017-32741.jpg?w=1060&t=st=1678479362~exp=1678479962~hmac=132a4d19a5d06e5ae31014b50c9b67cb9111f67259e6f5d55b263ec90c128e1a') no-repeat right top;
  background-size: cover;
  background-color: blue;
}
.gray-scale {
  filter: grayscale(100%);
}
</style>


<script>

export default {
  data() {
    return {
      headers: [
        { "index": 0, "text": "RF", "value": "RF" },
        { "index": 1, "text": "AnoIni", "value": "AnoIni"},
        { "index": 2, "text": "RPF", "value": "RPF"},
        { "index": 3, "text": "AnoFim", "value": "AnoFim"},
        { "index": 4, "text": "OpeNome", "value": "OpeNome"},
        { "index": 5, "text": "NomeTributo", "value": "NomeTributo"},
        { "index": 6, "text": "Proc_Nr", "value": "Proc_Nr"},
        { "index": 7, "text": "UnidadeAtual", "value": "UnidadeAtual"},
        { "index": 8, "text": "Munic", "value": "Munic"},
        { "index": 9, "text": "ACT", "value": "ACT"},
        { "index": 10, "text": "CNAE", "value": "CNAE"},
        { "index": 11, "text": "Atividade", "value": "Atividade"},
        { "index": 12, "text": "Dif", "value": "Dif"},
        { "index": 13, "text": "Esp", "value": "Esp"},
        { "index": 14, "text": "ME_S", "value": "ME_S"},
        { "index": 15, "text": "Paex", "value": "Paex"},
        { "index": 16, "text": "Refis", "value": "Refis"},
        { "index": 17, "text": "Simples", "value": "Simples"},
        { "index": 18, "text": "Empresa", "value": "Empresa"},
        { "index": 19, "text": "Cadastro", "value": "Cadastro"},
        { "index": 20, "text": "CadMotivo", "value": "CadMotivo"},
        { "index": 21, "text": "Ocupacao", "value": "Ocupacao"},
        { "index": 22, "text": "Prior", "value": "Prior"},
        { "index": 23, "text": "SitAtual", "value": "SitAtual"},
        { "index": 24, "text": "Valor", "value": "Valor"}
      ],
      items: [
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"LR - OUTRAS DESPESAS OPERACIONAIS", NomeTributo:"IRPJ  - Imposto de Renda Pessoas Jurídicas", Proc_Nr:"14041720221201944", UnidadeAtual:"PGFN", Munic:"Brasília - DF", ACT:"01.20.501.4238", CNAE:"Distribuição de energia elétrica", Atividade:"Acompanhar Processo Inscrito", Dif:"Não", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"NÃO INFORMADO", SitAtual:"Enviado A PFN", Valor:"28373938,14" },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"LR - OUTRAS DESPESAS OPERACIONAIS", NomeTributo:"IRPJ  - Imposto de Renda Pessoas Jurídicas", Proc_Nr:"14041720221201944", UnidadeAtual:"PGFN", Munic:"Brasília - DF", ACT:"01.20.501.4238", CNAE:"Distribuição de energia elétrica", Atividade:"Acompanhar Processo Inscrito", Dif:"Sim", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"NÃO INFORMADO", SitAtual:"Enviado A PFN", Valor:"28373938,14",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"LR - OUTRAS DESPESAS OPERACIONAIS", NomeTributo:"IRPJ  - Imposto de Renda Pessoas Jurídicas", Proc_Nr:"14041720221201944", UnidadeAtual:"PGFN", Munic:"Brasília - DF", ACT:"01.20.501.4238", CNAE:"Distribuição de energia elétrica", Atividade:"Acompanhar Processo Inscrito", Dif:"Sim", Esp:"Sim", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"NÃO INFORMADO", SitAtual:"Enviado A PFN", Valor:"28373938,14",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"LR - OUTRAS DESPESAS OPERACIONAIS", NomeTributo:"PIS - Contribuição para o Programa", Proc_Nr:"14041720220201908", UnidadeAtual:"CARF", Munic:"Brasília - DF", ACT:"01.63.963.1444", CNAE:"Distribuição de energia elétrica", Atividade:"Tratar CONTENCIOSO - Distribuição", Dif:"Não", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"02 - EXIGÊNCIA CT > 15MILHÕES", SitAtual:"REC. VOLUNTÁRIO EM JULGAMENTO", Valor:"2337202,56",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"LR - OUTRAS DESPESAS OPERACIONAIS", NomeTributo:"PIS - Contribuição para o Programa", Proc_Nr:"14041720220201908", UnidadeAtual:"CARF", Munic:"Brasília - DF", ACT:"01.63.963.1444", CNAE:"Distribuição de energia elétrica", Atividade:"Tratar CONTENCIOSO - Distribuição", Dif:"Sim", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"02 - EXIGÊNCIA CT > 15MILHÕES", SitAtual:"REC. VOLUNTÁRIO EM JULGAMENTO", Valor:"2337202,56",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"LR - OUTRAS DESPESAS OPERACIONAIS", NomeTributo:"PIS - Contribuição para o Programa", Proc_Nr:"14041720220201908", UnidadeAtual:"CARF", Munic:"Brasília - DF", ACT:"01.63.963.1444", CNAE:"Distribuição de energia elétrica", Atividade:"Tratar CONTENCIOSO - Distribuição", Dif:"Sim", Esp:"Sim", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"02 - EXIGÊNCIA CT > 15MILHÕES", SitAtual:"REC. VOLUNTÁRIO EM JULGAMENTO", Valor:"2337202,56",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"LR - OUTRAS DESPESAS OPERACIONAIS", NomeTributo:"Cofins - Contribuição para Financiamento da Seguridade Social", Proc_Nr:"14041720220201908", UnidadeAtual:"CARF", Munic:"Brasília - DF", ACT:"01.63.963.1444", CNAE:"Distribuição de energia elétrica", Atividade:"Tratar CONTENCIOSO - Distribuição", Dif:"Não", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"02 - EXIGÊNCIA CT > 15MILHÕES", SitAtual:"REC. VOLUNTÁRIO EM JULGAMENTO", Valor:"10765296,82",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"LR - OUTRAS DESPESAS OPERACIONAIS", NomeTributo:"Cofins - Contribuição para Financiamento da Seguridade Social", Proc_Nr:"14041720220201908", UnidadeAtual:"CARF", Munic:"Brasília - DF", ACT:"01.63.963.1444", CNAE:"Distribuição de energia elétrica", Atividade:"Tratar CONTENCIOSO - Distribuição", Dif:"Sim", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"02 - EXIGÊNCIA CT > 15MILHÕES", SitAtual:"REC. VOLUNTÁRIO EM JULGAMENTO", Valor:"10765296,82",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"LR - OUTRAS DESPESAS OPERACIONAIS", NomeTributo:"Cofins - Contribuição para Financiamento da Seguridade Social", Proc_Nr:"14041720220201908", UnidadeAtual:"CARF", Munic:"Brasília - DF", ACT:"01.63.963.1444", CNAE:"Distribuição de energia elétrica", Atividade:"Tratar CONTENCIOSO - Distribuição", Dif:"Sim", Esp:"Sim", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"02 - EXIGÊNCIA CT > 15MILHÕES", SitAtual:"REC. VOLUNTÁRIO EM JULGAMENTO", Valor:"10765296,82",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"LR - OUTRAS DESPESAS OPERACIONAIS", NomeTributo:"CSLL - Contribuição Social sobre Lucro Líquido", Proc_Nr:"14041720221201944", UnidadeAtual:"PGFN", Munic:"Brasília - DF", ACT:"01.20.501.4238", CNAE:"Distribuição de energia elétrica", Atividade:"Acompanhar Processo Inscrito", Dif:"Não", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"NÃO INFORMADO", SitAtual:"Enviado A PFN", Valor:"10229737,74",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"LR - OUTRAS DESPESAS OPERACIONAIS", NomeTributo:"CSLL - Contribuição Social sobre Lucro Líquido", Proc_Nr:"14041720221201944", UnidadeAtual:"PGFN", Munic:"Brasília - DF", ACT:"01.20.501.4238", CNAE:"Distribuição de energia elétrica", Atividade:"Acompanhar Processo Inscrito", Dif:"Sim", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"NÃO INFORMADO", SitAtual:"Enviado A PFN", Valor:"10229737,74",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"LR - OUTRAS DESPESAS OPERACIONAIS", NomeTributo:"CSLL - Contribuição Social sobre Lucro Líquido", Proc_Nr:"14041720221201944", UnidadeAtual:"PGFN", Munic:"Brasília - DF", ACT:"01.20.501.4238", CNAE:"Distribuição de energia elétrica", Atividade:"Acompanhar Processo Inscrito", Dif:"Sim", Esp:"Sim", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"NÃO INFORMADO", SitAtual:"Enviado A PFN", Valor:"10229737,74",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"PIS - CRÉDITOS DECORRENTES DA NÃO CUMULATIVIDADE", NomeTributo:"IRPJ  - Imposto de Renda Pessoas Jurídicas", Proc_Nr:"14041720221201944", UnidadeAtual:"PGFN", Munic:"Brasília - DF", ACT:"01.20.501.4238", CNAE:"Distribuição de energia elétrica", Atividade:"Acompanhar Processo Inscrito", Dif:"Não", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"NÃO INFORMADO", SitAtual:"Enviado A PFN", Valor:"28373938,14",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"PIS - CRÉDITOS DECORRENTES DA NÃO CUMULATIVIDADE", NomeTributo:"IRPJ  - Imposto de Renda Pessoas Jurídicas", Proc_Nr:"14041720221201944", UnidadeAtual:"PGFN", Munic:"Brasília - DF", ACT:"01.20.501.4238", CNAE:"Distribuição de energia elétrica", Atividade:"Acompanhar Processo Inscrito", Dif:"Sim", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"NÃO INFORMADO", SitAtual:"Enviado A PFN", Valor:"28373938,14",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"PIS - CRÉDITOS DECORRENTES DA NÃO CUMULATIVIDADE", NomeTributo:"IRPJ  - Imposto de Renda Pessoas Jurídicas", Proc_Nr:"14041720221201944", UnidadeAtual:"PGFN", Munic:"Brasília - DF", ACT:"01.20.501.4238", CNAE:"Distribuição de energia elétrica", Atividade:"Acompanhar Processo Inscrito", Dif:"Sim", Esp:"Sim", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"NÃO INFORMADO", SitAtual:"Enviado A PFN", Valor:"28373938,14",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"PIS - CRÉDITOS DECORRENTES DA NÃO CUMULATIVIDADE", NomeTributo:"PIS - Contribuição para o Programa", Proc_Nr:"14041720220201908", UnidadeAtual:"CARF", Munic:"Brasília - DF", ACT:"01.63.963.1444", CNAE:"Distribuição de energia elétrica", Atividade:"Tratar CONTENCIOSO - Distribuição", Dif:"Não", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"02 - EXIGÊNCIA CT > 15MILHÕES", SitAtual:"REC. VOLUNTÁRIO EM JULGAMENTO", Valor:"2337202,56",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"PIS - CRÉDITOS DECORRENTES DA NÃO CUMULATIVIDADE", NomeTributo:"PIS - Contribuição para o Programa", Proc_Nr:"14041720220201908", UnidadeAtual:"CARF", Munic:"Brasília - DF", ACT:"01.63.963.1444", CNAE:"Distribuição de energia elétrica", Atividade:"Tratar CONTENCIOSO - Distribuição", Dif:"Sim", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"02 - EXIGÊNCIA CT > 15MILHÕES", SitAtual:"REC. VOLUNTÁRIO EM JULGAMENTO", Valor:"2337202,56",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"PIS - CRÉDITOS DECORRENTES DA NÃO CUMULATIVIDADE", NomeTributo:"PIS - Contribuição para o Programa", Proc_Nr:"14041720220201908", UnidadeAtual:"CARF", Munic:"Brasília - DF", ACT:"01.63.963.1444", CNAE:"Distribuição de energia elétrica", Atividade:"Tratar CONTENCIOSO - Distribuição", Dif:"Sim", Esp:"Sim", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"02 - EXIGÊNCIA CT > 15MILHÕES", SitAtual:"REC. VOLUNTÁRIO EM JULGAMENTO", Valor:"2337202,56",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"PIS - CRÉDITOS DECORRENTES DA NÃO CUMULATIVIDADE", NomeTributo:"Cofins - Contribuição para Financiamento da Seguridade Social", Proc_Nr:"14041720220201908", UnidadeAtual:"CARF", Munic:"Brasília - DF", ACT:"01.63.963.1444", CNAE:"Distribuição de energia elétrica", Atividade:"Tratar CONTENCIOSO - Distribuição", Dif:"Não", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"02 - EXIGÊNCIA CT > 15MILHÕES", SitAtual:"REC. VOLUNTÁRIO EM JULGAMENTO", Valor:"10765296,82",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"PIS - CRÉDITOS DECORRENTES DA NÃO CUMULATIVIDADE", NomeTributo:"Cofins - Contribuição para Financiamento da Seguridade Social", Proc_Nr:"14041720220201908", UnidadeAtual:"CARF", Munic:"Brasília - DF", ACT:"01.63.963.1444", CNAE:"Distribuição de energia elétrica", Atividade:"Tratar CONTENCIOSO - Distribuição", Dif:"Sim", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"02 - EXIGÊNCIA CT > 15MILHÕES", SitAtual:"REC. VOLUNTÁRIO EM JULGAMENTO", Valor:"10765296,82",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"PIS - CRÉDITOS DECORRENTES DA NÃO CUMULATIVIDADE", NomeTributo:"Cofins - Contribuição para Financiamento da Seguridade Social", Proc_Nr:"14041720220201908", UnidadeAtual:"CARF", Munic:"Brasília - DF", ACT:"01.63.963.1444", CNAE:"Distribuição de energia elétrica", Atividade:"Tratar CONTENCIOSO - Distribuição", Dif:"Sim", Esp:"Sim", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"02 - EXIGÊNCIA CT > 15MILHÕES", SitAtual:"REC. VOLUNTÁRIO EM JULGAMENTO", Valor:"10765296,82",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"PIS - CRÉDITOS DECORRENTES DA NÃO CUMULATIVIDADE", NomeTributo:"CSLL - Contribuição Social sobre Lucro Líquido", Proc_Nr:"14041720221201944", UnidadeAtual:"PGFN", Munic:"Brasília - DF", ACT:"01.20.501.4238", CNAE:"Distribuição de energia elétrica", Atividade:"Acompanhar Processo Inscrito", Dif:"Não", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"NÃO INFORMADO", SitAtual:"Enviado A PFN", Valor:"10229737,74",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"PIS - CRÉDITOS DECORRENTES DA NÃO CUMULATIVIDADE", NomeTributo:"CSLL - Contribuição Social sobre Lucro Líquido", Proc_Nr:"14041720221201944", UnidadeAtual:"PGFN", Munic:"Brasília - DF", ACT:"01.20.501.4238", CNAE:"Distribuição de energia elétrica", Atividade:"Acompanhar Processo Inscrito", Dif:"Sim", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"NÃO INFORMADO", SitAtual:"Enviado A PFN", Valor:"10229737,74",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"PIS - CRÉDITOS DECORRENTES DA NÃO CUMULATIVIDADE", NomeTributo:"CSLL - Contribuição Social sobre Lucro Líquido", Proc_Nr:"14041720221201944", UnidadeAtual:"PGFN", Munic:"Brasília - DF", ACT:"01.20.501.4238", CNAE:"Distribuição de energia elétrica", Atividade:"Acompanhar Processo Inscrito", Dif:"Sim", Esp:"Sim", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"NÃO INFORMADO", SitAtual:"Enviado A PFN", Valor:"10229737,74",  },
        { RF:"01", AnoIni:"2018", RPF:"0110100.2018.00052", AnoFim:"2019", OpeNome:"COFINS - CRÉDITOS DECORRENTES DA NÃO CUMULATIVIDADE", NomeTributo:"IRPJ  - Imposto de Renda Pessoas Jurídicas", Proc_Nr:"14041720221201944", UnidadeAtual:"PGFN", Munic:"Brasília - DF", ACT:"01.20.501.4238", CNAE:"Distribuição de energia elétrica", Atividade:"Acompanhar Processo Inscrito", Dif:"Não", Esp:"Não", ME_S:"Não", Paex:"Não", Refis:"Não", Simples:"Não", Empresa:"NEOENERGIA DISTRIBUICAO BRASILIA S.A.", Cadastro:"Ativa", CadMotivo:"NÃO INFORMADO", Ocupacao:"Não se aplica", Prior:"NÃO INFORMADO", SitAtual:"Enviado A PFN", Valor:"28373938,14",  },
      ],
    };
  },
};

</script>